apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: apisix-adc-sync

resources:
  - adc-sync-job.yaml

commonLabels:
  app.kubernetes.io/part-of: apisix-adc-sync
  app.kubernetes.io/managed-by: argocd

