apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: apisix-gateway-api

namespace: apisix-argocd

resources:
  - gatewayclass.yaml
  - gateway.yaml
  - gatewayproxy.yaml
  - httproute-v1.yaml
  - httproute-v4.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: apisix-gateway-api
      app.kubernetes.io/managed-by: argocd

